uploads = []
outputs = []

[[generated]]
id = "IBSAe2M0H0nJne8_KkH_s"
uri = "file://artifacts/multi-ai/assets/images/icon.png"
type = "image"
title = "multi-ai app icon"

[[generated]]
id = "LvVHblKQO34xqAXVFOOsN"
uri = "file://artifacts/multi-ai/assets/images/bg-alley.png"
type = "image"
title = "noir cyberpunk alleyway background"
