// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screenshots/HD_HomeEmpty.tsx": () => import("../components/mockups/screenshots/HD_HomeEmpty.tsx"),
  "./components/mockups/screenshots/HD_HomeResponding.tsx": () => import("../components/mockups/screenshots/HD_HomeResponding.tsx"),
  "./components/mockups/screenshots/HD_Pricing.tsx": () => import("../components/mockups/screenshots/HD_Pricing.tsx"),
  "./components/mockups/screenshots/HD_Synthesis.tsx": () => import("../components/mockups/screenshots/HD_Synthesis.tsx"),
  "./components/mockups/screenshots/HD_Thread.tsx": () => import("../components/mockups/screenshots/HD_Thread.tsx"),
  "./components/mockups/screenshots/HomeEmpty.tsx": () => import("../components/mockups/screenshots/HomeEmpty.tsx"),
  "./components/mockups/screenshots/HomeResponding.tsx": () => import("../components/mockups/screenshots/HomeResponding.tsx"),
  "./components/mockups/screenshots/Pricing.tsx": () => import("../components/mockups/screenshots/Pricing.tsx"),
  "./components/mockups/screenshots/Synthesis.tsx": () => import("../components/mockups/screenshots/Synthesis.tsx"),
  "./components/mockups/screenshots/Thread.tsx": () => import("../components/mockups/screenshots/Thread.tsx")
};
